### ISSUE TITLE
The r2r-js client has no option to disable posthog data collection

### ISSUE THREAD

**Issue by yaohuiwu** [SciPhi-AI/r2r-js#51]
**Describe the bug**
There is no option for the developer to disable the posthog data collection.

I added a fake dns record to the /ect/hosts. It always stuck for a long time until timeout.

console.error
      Error while shutting down PostHog PostHogFetchNetworkError: Network error while fetching PostHog
          at retriable (/usr/local/src/web/typescript/R2R-client-demo/node_modules/posthog-core/src/index.ts:645:17)
          at processTicksAndRejections (node:internal/process/task_queues:95:5)
          at retriable (/usr/local/src/web/typescript/R2R-client-demo/node_modules/posthog-core/src/utils.ts:27:19)
          at PostHog.fetchWithRetry (/usr/local/src/web/typescript/R2R-client-demo/node_modules/posthog-core/src/index.ts:635:12)
          at PostHog._flush (/usr/local/src/web/typescript/R2R-client-demo/node_modules/posthog-core/src/index.ts:605:7) {
        error: TypeError: fetch failed
            at node:internal/deps/undici/undici:12344:11
            at processTicksAndRejections (node:internal/process/task_queues:95:5)
            at retriable (/usr/local/src/web/typescript/R2R-client-demo/node_modules/posthog-core/src/index.ts:639:17)
            at retriable (/usr/local/src/web/typescript/R2R-client-demo/node_modules/posthog-core/src/utils.ts:27:19)
            at PostHog.fetchWithRetry (/usr/local/src/web/typescript/R2R-client-demo/node_modules/posthog-core/src/index.ts:635:12)
            at PostHog._flush (/usr/local/src/web/typescript/R2R-client-demo/node_modules/posthog-core/src/index.ts:605:7) {
          cause: Error: connect ECONNREFUSED 127.0.0.1:443
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
            errno: -61,
            code: 'ECONNREFUSED',
            syscall: 'connect',
            address: '127.0.0.1',
            port: 443
          }
        }
      }

**To Reproduce**

**Expected behavior**
The Client object should have a disablePosthog option.

export declare class r2rClient {
    private axiosInstance;
    private baseUrl;
    private accessToken;
    private refreshToken;
    constructor(baseURL: string, prefix?: string);

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NolanTrem** [comment]
Hey @yaohuiwu you should be able to disable telemetry by setting the R2R_JS_DISABLE_TELEMETRY environment variable to "true".

If you're using `pnpm dev` or `pnpm start`, you can simply pass the environment variable in the command itself:

```
R2R_JS_DISABLE_TELEMETRY=true pnpm dev
```

or

```
R2R_JS_DISABLE_TELEMETRY=true pnpm start
```

This will disable telemetry for that specific run of your development or start script without needing to modify any configuration files.

If you're on Windows and not using a Unix-like shell, you might need to use the `set` command:

```
set R2R_JS_DISABLE_TELEMETRY=true && pnpm dev
```

Let me know if you have any questions or issues around this!

**Comment by yaohuiwu** [comment]
@NolanTrem I added the R2R_JS_DISABLE_TELEMETRY=true to the test script in package.json. It works. Thanks.

`  "scripts": {
    "test": "R2R_JS_DISABLE_TELEMETRY=true jest"
  }`
